### ISSUE TITLE
密钥的定义有规则吗？只可加密核心代码的意思是？

### ISSUE THREAD

**Issue by smartymoon** [lihancong/tonyenc#1]

**Comment by lihancong** [comment]
1.密钥可以长一点，没有其他限制
2.整个项目的 php 文件很多的话，可以只加密一部分重要的代码

**Comment by lihancong** [comment]
> 密钥的定义有规则吗？只可加密核心代码的意思是？
1.密钥可以长一点，没有其他限制
2.整个项目的 php 文件很多的话，可以只加密一部分重要的代码

**Comment by lihancong** [comment]
> 密钥的定义有规则吗？只可加密核心代码的意思是？

1.密钥可以长一点，没有其他限制
2.整个项目的 php 文件很多的话，可以只加密一部分重要的代码
