### ISSUE TITLE
内存泄露的fixed出错了，导致页面乱码了。

### ISSUE THREAD

**Issue by amhoho** [lihancong/tonyenc#19]
使用最新的代码加密后，打开页面成了乱码，经查是这里的fixed出错了，而还原就正常。https://github.com/lihancong/tonyenc/commit/a4f51c495c42b2b7321b3029b25c5d6373ee746a

**Comment by tsln1998** [comment]
不懂PHP源码，刚刚也遇到了这个问题
有A、B、C三个文件如下:
A:
`<?php require(‘./C.php');`

B:
`<?php require('./C/php’);`

C:
`<?php phpinfo();`


B和C文件使用tonyenc加密。A文件不加密

现在直接执行C文件可正常输出，而通过A或B文件去require C的时候。会乱码
