### ISSUE TITLE
PHP 7.0.8下编译安装失败

### ISSUE THREAD

**Issue by zhangya4548** [lihancong/tonyenc#2]
Libraries have been installed in:
   /home/vagrant/tonyenc/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------

Build complete.
Don't forget to run 'make test'.

vagrant@homestead:~/tonyenc$ make install
Installing shared extensions:     /usr/lib/php/20151012/
cp: cannot create regular file '/usr/lib/php/20151012/#INST@3820#': Permission denied
Makefile:87: recipe for target 'install-modules' failed
make: *** [install-modules] Error 1

**Comment by lihancong** [comment]
> make: *** [install-modules] Error 1

仅 make 就行，不用 make install
