### ISSUE TITLE
安全性欠佳...获取扩展之后很容易就破解了.

### ISSUE THREAD

**Issue by amhoho** [lihancong/tonyenc#24]
我对代码解密了之后,出于安全考虑,尝试劫持zend,在扩展前载入个劫持zend的扩展,结果十分轻松的就获取内容了...建议搞搞秘匙之类更安全的方式.

**Comment by feng99** [comment]
core.h
/* 这里指定密钥，长一些更安全 */
const u_char tonyenc_key[] = {
        0x9f, 0x49, 0x52, 0x00,
        0x58, 0x9f, 0xff, 0x21,
        0x3e, 0xfe, 0xea, 0xfa,
        0xa6, 0x33, 0xf3, 0xc6,
};

有秘钥呀
