### ISSUE TITLE
win下使用不了，我的版本是7.0.1

### ISSUE THREAD

**Issue by Benny66** [lihancong/tonyenc#27]
[26-May-2020 05:38:23 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'D:/ipwebV2/PHP7/ext\php_tonyenc_php70_x64_nts.dll' - %1 不是有效的 Win32 应用程序。
 in Unknown on line 0

**Comment by Benny66** [comment]
![image](https://user-images.githubusercontent.com/31094171/82866725-0ea93800-9f5c-11ea-8286-cd0dbd5eef48.png)
![image](https://user-images.githubusercontent.com/31094171/82866769-1ff24480-9f5c-11ea-88a9-ae56d48240e4.png)
![image](https://user-images.githubusercontent.com/31094171/82866794-2aacd980-9f5c-11ea-91a3-355830a07b1c.png)

**Comment by Benny66** [comment]
已添加php.ini配置：extension=php_tonyenc_php70_x64_nts.dll
phpinfo中：
Configuration File (php.ini) Path | C:\Windows
Loaded Configuration File | D:\ipwebV2\PHP7\php.ini

dll扩展文件也已经放在目录：D:\ipwebV2\PHP7\ext

**Comment by lihancong** [comment]
你这32位

**Comment by Benny66** [comment]
不用了，谢谢了哈，我自己编译了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tony"<notifications@github.com&gt;; 
发送时间: 2020年7月3日(星期五) 上午10:00
收件人: "lihancong/tonyenc"<tonyenc@noreply.github.com&gt;; 
抄送: "Benny"<2283743369@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lihancong/tonyenc] win下使用不了，我的版本是7.0.1 (#27)





 
你这32位
