### ISSUE TITLE
不是有效的 Win32 应用程 序

### ISSUE THREAD

**Issue by zztj** [lihancong/tonyenc#3]
win10 64位,php7.0+nginx
我在php.ini中加入这个
extension=php_tonyenc_php70_x64_ts.dll
vc14 安装的64位的
按照你写的例子执行后报错如下：
PHP Warning:  PHP Startup: Unable to load dynamic library 'D:\phpStudy\php\php-7.0.12-nts\ext\php_tonyenc_php70_x64_ts.dll' - %1 不是有效的 Win32 应用程 序。

**Comment by lihancong** [comment]
PHP 是不是 64 位

**Comment by lihancong** [comment]
php是不是64位

**Comment by lihancong** [comment]
> win10 64位,php7.0+nginx
> 我在php.ini中加入这个
> extension=php_tonyenc_php70_x64_ts.dll
> vc14 安装的64位的
> 按照你写的例子执行后报错如下：
> PHP Warning: PHP Startup: Unable to load dynamic library 'D:\phpStudy\php\php-7.0.12-nts\ext\php_tonyenc_php70_x64_ts.dll' - %1 不是有效的 Win32 应用程 序。

PHP 是不是 64 位的，是不是线程安全，全部要匹配才行
