### ISSUE TITLE
Warning: PHP Startup: tonyenc: Unable to initialize module

### ISSUE THREAD

**Issue by hulang** [lihancong/tonyenc#33]
win10 x64，用的：Laragon，PHP版本：php-7.2.19-Win32-VC15-x64

下载后，用的：php_tonyenc_php70_x64_ts.dll版本
在php.ini中加入：
extension=php_tonyenc_php70_x64_ts

在命令行下：php -v 就提示如下。。哪里搞错了？

Warning: PHP Startup: tonyenc: Unable to initialize module
Module compiled with module API=20151012
PHP    compiled with module API=20170718
These options need to match
 in Unknown on line 0

**Comment by lihancong** [comment]
> php70_x64_ts.dll版本

**Comment by hulang** [comment]
@lihancong 我下载的就是啊。。。你这样回复有意义么？

**Comment by hulang** [comment]
算了。。我彩笔搞不来。。。

**Comment by lihancong** [comment]
> 算了。。我彩笔搞不来。。。

你自己版本用错了怪我咯

**Comment by lihancong** [comment]
> 我下载的就是啊。。。你这样回复有意义么？

你版本用错了，我写的就是7.0的，编译方法我也写了，怪我咯

**Comment by lihancong** [comment]
> 我下载的就是啊。。。你这样回复有意义么？

你版本用错了，我写的就是7.0的，你的版本的编译方法我也写了
