### ISSUE TITLE
不知道是不是跟composer冲突？

### ISSUE THREAD

**Issue by if1024** [lihancong/tonyenc#4]
我服务器上测试一段时间后，突然发下composer跑不起来了，
情况如下，
![image](https://user-images.githubusercontent.com/16129621/27011648-dd2283b6-4ef2-11e7-8683-44c6b7e370f4.png)
各种重装啥的搞了一遍没解决，PHP都被我升级到了7.1.6的版本还是不行。然后我取消到这个扩展就没问题。我没搞懂是为啥，所以问问作者。谢谢

**Comment by lihancong** [comment]
> 各种重装啥的搞了一遍没解决，PHP都被我升级到了7.1.6的版本还是不行。然后我取消到这个扩展就没问题。我没搞懂是为啥，所以问问作者。谢谢

是最新的扩展代码吗？看下 composer 24行有什么
