### ISSUE TITLE
x86位编译异常

### ISSUE THREAD

**Issue by YDsocial** [lihancong/tonyenc#5]
1>------ 已启动生成: 项目: TONYENC, 配置: Release Win32 ------
1>tonyenc.c
1>C:\php-7.1.6\win32/ioutil.h(372): warning C4996: '_wfopen': This function or variable may be unsafe. Consider using _wfopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\ucrt\corecrt_wstdio.h(130): note: 参见“_wfopen”的声明
1>C:\php-7.1.6\win32/ioutil.h(479): warning C4018: “>”: 有符号/无符号不匹配
1>c:\tonyenc-master\core.h(56): warning C4018: “>”: 有符号/无符号不匹配
1>c:\tonyenc-master\core.h(66): warning C4996: 'fileno': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _fileno. See online help for details.
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\ucrt\stdio.h(2450): note: 参见“fileno”的声明
1>c:\tonyenc-master\core.h(83): warning C4996: 'close': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _close. See online help for details.
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\ucrt\corecrt_io.h(459): note: 参见“close”的声明
1>c:\tonyenc-master\core.h(105): warning C4101: “write_len”: 未引用的局部变量
1>LINK : warning LNK4075: 忽略“/INCREMENTAL”(由于“/OPT:ICF”规范)
1>  正在创建库 C:\tonyenc-master\Release\TONYENC.lib 和对象 C:\tonyenc-master\Release\TONYENC.exp
1>TONYENC.vcxproj -> C:\tonyenc-master\Release\TONYENC.dll
1>TONYENC.vcxproj -> C:\tonyenc-master\Release\TONYENC.pdb (Full PDB)
1>已完成生成项目“TONYENC.vcxproj”的操作。
========== 生成: 成功 1 个，失败 0 个，最新 0 个，跳过 0 个 ==========
配置: Release Win64 成功编译,并且测试正常.请求指导win32编译方法.谢谢您的好项目.

**Comment by lihancong** [comment]
> 请求指导win32编译方法

PHP 下载32位，VS 里面选择32位编译

**Comment by YDsocial** [comment]
@lihancong 
是的先生,我就是这样子做的.php-7.1.6-nts-Win32-VC14-x86,但是结局并不是我想要的.而且产生了1楼的错误日记.编译出来的DLL可以在32位php使用,但是DLL的大小仅有10kb.这里面一定有什么错误.
