### ISSUE TITLE
加密后，无法正常执行了

### ISSUE THREAD

**Issue by jovicisco** [lihancong/tonyenc#6]
php7.0.20
Laravel 5.2
apache 2.4.6

加密正常，但是执行时出现了问题：
![1](https://user-images.githubusercontent.com/26062499/28160592-4cddac6c-67f3-11e7-985f-37c20e393825.JPG)

F12信息如下：
![2](https://user-images.githubusercontent.com/26062499/28160635-6bfedce2-67f3-11e7-9fa1-ae5b47dee47e.JPG)

请指教，谢谢。

**Comment by lihancong** [comment]
> 请指教

你是不是把 js 也加密了
