### ISSUE TITLE
无法加载动态库

### ISSUE THREAD

**Issue by XKangs** [lihancong/tonyenc#7]
使用的是预编译好的dll
php.ini中添加了
extension=php_tonyenc_php70_x64_ts.dll

启动后报错
Warning: PHP Startup: Unable to load dynamic library 'C:\Soft\xampp\php\ext\php_tonyenc_php70_x64_ts.dll' - %1 不是有效 的 Win32 应用程序。
 in Unknown on line 0

OS：Win10
PHP Version 7.1.7 TS

**Comment by lihancong** [comment]
> 使用的是预编译好的dll
> php.ini中添加了
> extension=php_tonyenc_php70_x64_ts.dll
> 
> 启动后报错
> Warning: PHP Startup: Unable to load dynamic library 'C:\Soft\xampp\php\ext\php_tonyenc_php70_x64_ts.dll' - %1 不是有效 的 Win32 应用程序。
> in Unknown on line 0
> 
> OS：Win10
> PHP Version 7.1.7 TS

php是64位吗

**Comment by XKangs** [comment]
不是，但是您也没提供32位编译好的dll呀
